name: Experience12
favicon: null
layout_spectrum: 0.8237
typography_spectrum: 0.23025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7876191041432321
  lightness: 0.13448080839589238
  saturation: 0.8125
  rhythmicContrast: 0.863256171811372
purpose: []
